# Copyright 2026 The flink-gcp authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

replicas: 0
watchNamespaces:
  - tier3-smoke
webhook:
  create: false
image:
  repository: apache/flink-kubernetes-operator
  tag: "1.15.0"
  digest: ""
operatorServiceAccount:
  create: true
  name: flink-operator
jobServiceAccount:
  create: false
rbac:
  create: true
  nodesRule:
    create: false
  operatorRole:
    create: true
    name: flink-operator
  operatorRoleBinding:
    create: true
    name: flink-operator-role-binding
  jobRole:
    create: false
  jobRoleBinding:
    create: false
